### ISSUE TITLE
Cannot find module 'broccoli-stew'

### ISSUE THREAD

**Issue by ngyv** [FutoRicky/ember-cli-dropzonejs#83]
Ran into this error when I updated to the latest version.
```
Error: Cannot find module 'broccoli-stew'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/me/Desktop/project/node_modules/ember-cli-dropzonejs/index.js:8:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Fixed when I revert to `1.0.0`.

**Comment by ngyv** [comment]
Alternatively, add `broccoli-stew` in devDependencies before `ember-cli-dropzonejs`. Don't think it's an issue with this per se but leaving this here in case people are searching.

**Comment by FutoRicky** [comment]
Is this error preventing the addon from working on your side? I'm unable to recreate this error.

**Comment by ngyv** [comment]
Hmm I can't run dev server on `ember server`.

**Comment by FutoRicky** [comment]
@ngyv What ember version are you using?

**Comment by ngyv** [comment]
2.13.4

**Comment by FutoRicky** [comment]
@ngyv Sorry for the inactivity on this. Are you still having this issue?

**Comment by ngyv** [comment]
👍  No longer an issue after I upgraded ember-cli to 2.14.2.
